<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'webui\\app\\apiprovider' => '/app/ApiProvider.php',
                'webui\\app\\app' => '/app/App.php',
                'webui\\app\\appconfiguration' => '/app/AppConfig.php',
                'webui\\app\\components\\shared\\footer' => '/app/components/shared/Footer.php',
                'webui\\app\\components\\shared\\head' => '/app/components/shared/Head.php',
                'webui\\app\\templates\\basetemplate' => '/app/templates/BaseTemplate.php',
                'webui\\app\\views\\homeview' => '/app/views/HomeView.php',
                'webui\\lib\\core\\component' => '/lib/core/Component.php',
                'webui\\lib\\core\\configuration' => '/lib/core/Configuration.php',
                'webui\\lib\\core\\dataprovider' => '/lib/core/DataProvider.php',
                'webui\\lib\\core\\engine' => '/lib/core/Engine.php',
                'webui\\lib\\core\\template' => '/lib/core/Template.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
