version: "3.8"

services:
  webserver:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8081:8081"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - backend

  backend:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    environment:
      GONO_STATIC: "${GONO_STATIC}"
    volumes:
      - ./UI/static:/opt/static

